font_family GeistMono Nerd Font
font_size 12

disable_ligatures no
enable_audio_bell no


shell_integration disabled

url_style curly

cursor_blink_interval 0.7 
cursor_shape beam

remember_window_size yes
window_padding_width 10

background_opacity 0.6

confirm_os_window_close 0

sync_to_monitor no


#colors


# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
